services:
  - type: web
    name: portfolio
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: portfolio.onrender.com,localhost,127.0.0.1

